
#1. 1. Your app — builds from your Dockerfile, exposes the port, and waits for the database  
services:
  notes:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

#2.The database service — uses the official Postgres image, sets up environment variables, 
# and mounts a volume for data persistence
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

#3. A named volume for the database data
volumes:
  pgdata: